# Generated by Django 2.1.7 on 2019-05-15 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('Project', '0003_comment_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ProjectComment',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 3, 24, 49, 381619, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
