# Generated by Django 2.1.7 on 2019-05-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=31)),
                ('front_page_url', models.URLField()),
                ('pic_url', models.URLField()),
                ('logo_url', models.URLField()),
                ('supervisors', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='labcomment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabInfo'),
        ),
        migrations.AddField(
            model_name='labcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserAccount'),
        ),
    ]
