# Generated by Django 2.1.7 on 2019-05-26 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pw_hash', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_activated_time', models.DateTimeField(default=datetime.date.today)),
                ('real_name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(max_length=255, unique=True)),
                ('pic_url', models.URLField(max_length=512)),
                ('school', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField()),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='users.UserAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.UserAccount')),
            ],
        ),
    ]
