# Generated by Django 2.1.7 on 2019-05-16 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='seminarinfo',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarinfo',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.SeminarInfo'),
        ),
    ]
