# Generated by Django 2.1.7 on 2019-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='published date'),
        ),
    ]
