# Generated by Django 2.1.7 on 2019-05-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0003_auto_20190501_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='pub_date',
        ),
    ]
